---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: userservice
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: userservice
    spec:
      containers:
        - name: userservice
          image: rustbucket/userservice:latest
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_URLS
              value: http://*:80
  selector:
    matchLabels:
      app: userservice
---
apiVersion: v1
kind: Service
metadata:
  name: userservice
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: userservice
